### A Step-by-Step Guide on Streaming Data from AWS RDS Multi-AZ PostgreSQL DB to a Standlone PostgreSQL DB Using Debezium 0.7.1 Connector :

In this guide, I will share my experience on integrating AWS RDS PostgreSQL and Debezium Kafka 
Connector. So we will be able to stream data from AWS RDS PostgreSQL to an another standlone 
PostgreSQL DB on AWS EC2 Server.

Before working with Debezium, you need to make a decision on which connector will be "Source Connector" and 
which one will be "Sink Connector". In our example, "Source Connector" will connect to "AWS RDS Multi-AZ PostgreSQL DB, 
and "Sink Connector" will connect to Standlone PostgreSQL DB. 

Actually, the configuration below supports two-way connectors as well. Please keep in mind that only a single 
Debezium Kafka Connector can serve multiple tasks, it means to be able to use the same connector as source and 
sink  and can work one-to-many, many-to-one, one-to-one ways. 

### Prerequisites:
To be able to understand all the concepts mentioned here properly, you should be familiar with the systems 
like; debezium, docker, docker-compose, AWS RDS, PostgreSQL, Apache Kafka, Linux.
The guide assumes that you have setup an instance on AWS and installed the necessary apps on it. 
Before we go;
1 - First, you need to create an AWS EC2 Instance with Amazon Linux AMI as explained at this link. 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/launching-instance.html

2 - Second, it is required to install docker on the machine as explained at this link. 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html

3 - Lastly, it is required to install docker compose as explained at this link.
https://docs.docker.com/compose/install/#install-compose


### A.1 Streaming Data From AWS RDS PostgreSQL DB to a Postgresql Standalone DB:

### A.1.1 Topology

-------------------------     --------------------------     --------------------------      ----------------------------     -----------------
| AWS RDS PostgreSQL DB |---> |DEBEZIUM KAFKA CONNECTOR|---> | APACHE KAFKA SERVER    |--->  | DEBEZIUM KAFKA CONNECTOR |---> | POSTGRESQL DB |       
-------------------------     --------------------------     --------------------------      ----------------------------     -----------------

### A.1.2 AWS RDS PostgreSQL DB CONFIGURATION
--------------
1 - Create a new "Parameter Group" at AWS RDS "Parameter groups" section and give it a name , for example, "fairbit-postgres-db-parameter-groups"

2 - Be sure to set the new Parameter Group parameters as follows:
rds.logical_replication = 1
shared_preload_libraries = pg_stat_statements,pg_hint_plan,pgaudit
ssl=0

3 - Create a new AWS RDS PostgreSQL DB called moneratestserverwithnoreplica2. Set the user name as "moneradbuser". 
Give permission to Port Number TCP:5432 to all sources (0.0.0.0/0) via DB Security Group

4 - Connect to the database via psql 
'''
psql -h moneratestserverwithnoreplica2.cuwbhrbzgqk9.us-east-1.rds.amazonaws.com -d moneradb -U moneradbuser -p 5432
'''

5 - Type \d to see a screen like that and be sure that  your user moneradbuser is a member of rds_superuser and rds_superuser has "rds_replication" right
moneradb=> \du
                                                   List of roles
    Role name    |                         Attributes                         |              Member of
-----------------+------------------------------------------------------------+-------------------------------------
 moneradbuser    | Create role, Create DB                                    +| {rds_superuser}
                 | Password valid until infinity                              |
 rds_replication | Cannot login                                               | {}
 rds_superuser   | Cannot login                                               | {rds_replication,pg_signal_backend}
 rdsadmin        | Superuser, Create role, Create DB, Replication, Bypass RLS+| {}
                 | Password valid until infinity                              |
 rdsrepladmin    | No inheritance, Cannot login, Replication                  | {}
 

6 - Display if any replication slots are available
select * from pg_replication_slots;

7 - Create a replication plugin called wal2json and name  i wal2json_rds
SELECT * FROM pg_create_logical_replication_slot('wal2json_rds', 'wal2json');

8 - If you wanna delete the slot type this
SELECT pg_drop_replication_slot('wal2json_rds');

9 - Create a table named customers
CREATE TABLE customers (id SERIAL,  first_name VARCHAR(255) NOT NULL,  last_name VARCHAR(255) NOT NULL,  email VARCHAR(255) NOT NULL,  PRIMARY KEY(id));

10 - Change table so that it can support replication
ALTER TABLE customers REPLICA IDENTITY FULL;

11 - Insert some records into the source table
insert into customers values(default, 'John', 'Doe', 'john.doe@example.com');
insert into customers values(default, 'John2', 'Doe2', 'john2.doe@example.com');

***********************************
A.1.2 Prepare Debezium Test Environment And Complete Configuration On Linux
***********************************

1 - Create a directory under user home directory 
mkdir ~/debezium

2 - Download the sample config scripts and copy them into that directory
cp *.zip debezium/

3 - Enter into that directory
cd debezium

4 - export DEBEZIUM_VERSION environment variable
export DEBEZIUM_VERSION=0.7.1

5 - Build docker-compose files named docker-compose.yaml (default name)
docker-compose build

6 - Start the docker containers. Applications running on containers are Zookeper, Apache Kafka, Debezium Kafka Connector, PostgreSQL db) 
docker-compose up	

7 - Create a table named "customers" on target PostgreSQL db
docker-compose -f docker-compose.yaml exec postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB -c "CREATE TABLE customers (id SERIAL,  first_name VARCHAR(255) NOT NULL,  last_name VARCHAR(255) NOT NULL,  email VARCHAR(255) NOT NULL,  PRIMARY KEY(id));"'

8 - Start target connectors
8.1 * Start target PostgreSQL DB connector running in a container
curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:8083/connectors/ -d @jdbc-sink.json

8.2 * Start target (or sink) PostgreSQL DB connector running in a AWS EC2 Server
curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:8083/connectors/ -d @jdbc-sink-on-premise.json

9 - Start source AWS RDS PostgreSQL DB connector
curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:8083/connectors/ -d @source-postgres.json

10 - Verify that the connector definitions are added to the debezium connector
curl -H "Accept:application/json" localhost:8083/connectors/

11 - Verify that the PostgreSQL database has the same content as in AWS RDS PostgreSQL DB:
docker-compose -f docker-compose.yaml exec postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB -c "select * from customers"'

12- Optionally, if you wanna display the current db name, run the following command 
docker-compose -f docker-compose.yaml exec postgres bash -c 'psql -U $POSTGRES_USER $POSTGRES_DB -c "SELECT current_database();"'

13- Optionally, If you wanna login into PostgreSQL DB container with an of "f86dfa1bba34", run the following command 
docker exec -it f86dfa1bba34 bash

14 - Optionally, if you wanna restart the servers, press Ctrl + C and run the following command again
export DEBEZIUM_VERSION=0.7.1
docker-compose down
docker-compose up
--------------

### A.1.3 Prepare Postgresql Standalone Db Environment As A Source And Target(Sink) At The Same Time For Debezium Connector On Linux

Ref : https://linode.com/docs/databases/postgresql/how-to-install-postgresql-relational-databases-on-centos-7/

--------------
sudo yum update
cd ~
wget https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-5.noarch.rpm
sudo yum install pgdg-centos96-9.6-5.noarch.rpm epel-release
sudo yum update
sudo yum install postgresql96-server postgresql96-contrib

1 - Login as postgres linux user 
sudo -i -u postgres

2 - Start PostgreSQL DB server
/usr/lib64/pgsql96/bin/initdb -D /var/lib/pgsql96/data
/usr/lib64/pgsql96/bin/pg_ctl -D /var/lib/pgsql96/data -l logfile start


3 - Check out db server status
/usr/lib64/pgsql96/bin/pg_ctl status -D /var/lib/pgsql96/data

4 - Restart db server if needed
/usr/lib64/pgsql96/bin/pg_ctl restart -D /var/lib/pgsql96/data

5 - Set password for postgres linux user
sudo passwd postgres

6 - Set password for postgres db user
psql -d template1 -c "ALTER USER postgres WITH PASSWORD 'postgres';"

7 - Create a user named "postgresuser"
createuser postgresuser

8 - Create a db named "inventory"
createdb inventory -O postgresuser

9 - Set the new user's password
 psql -d inventory -c "ALTER USER postgresuser WITH PASSWORD 'postgrespw';"

10 - Connect to inventory db
 psql inventory
 
11 - Some useful commands
\l : list all databases
\h : list all command
\du : show user roles
\c : show connection info

12 - Go to db folder
cd /var/lib/pgsql96/data/

13 - open "pg_hba.conf" config file and change it as follows
vim pg_hba.conf

**** pg_hba.conf ****
# IPv4 local connections:
host    all             all             0.0.0.0/0               md5

# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                trust
#host    replication     postgres        127.0.0.1/32            trust
#host    replication     postgres        ::1/128                 trust
host     replication     postgresuser    0.0.0.0/0               md5
**** pg_hba.conf ****

14 - open "postgresql.conf" config file and change it as follows
vim postgresql.conf

**** postgresql.conf ****
listen_addresses = '*'
port = 5432
ssl = off
wal_level = logical
max_wal_senders = 1
max_replication_slots = 1 
**** postgresql.conf ****


15 - Restart the server to apply changes
/usr/lib64/pgsql96/bin/pg_ctl restart -D /var/lib/pgsql96/data

16 - Connect to the new db with the new user
psql -d inventory -U postgresuser

17 - Give REPLICATION and SUPERUSER(not mandatory) rights to the new user.

ALTER ROLE postgresuser WITH SUPERUSER; 
ALTER ROLE postgresuser WITH REPLICATION;


18 - Add your user postgres to the sudoers group
usermod -aG wheel postgres
cat /etc/sudoers

19 - Allow wheel user group to run all commands on linux
visudo

***** visudo *******
# Open wheel line
## Allows people in group wheel to run all commands
%wheel        ALL=(ALL)       ALL
***** visudo *******


20 - Find postgres development tools to compile wal2json plugin
yum list postgres*
sudo yum install postgresql96-devel.x86_64
yum list gcc*
sudo yum install gcc.noarch

21 - Install git tool to download wal2json plugin code from the repository below.
sudo yum install git
sudo -i -u postgres
git clone https://github.com/eulerto/wal2json.git

22 - Compile wal2json plugin
cd wal2json/
PATH=/path/to/bin/pg_config:$PATH
USE_PGXS=1 make
sudo /usr/bin/install -c -m 755  wal2json.so '/usr/lib64/pgsql96/'
### The same thing with (USE_PGXS=1 make install )


23 - Create a replication slot named "wal2json_rds" using the plugin "wal2json".
psql inventory -U postgresuser
SELECT * FROM pg_create_logical_replication_slot('wal2json_rds', 'wal2json');
SELECT * FROM pg_replication_slots;

24 - Check out your wal_level, you must see "logical"
show wal_level;
--------------
